version: '3.7'

networks:
  default:
    name: wallet_net

volumes:
  db-volume:


services:

  postgres:
    container_name: eth_wallet_postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: eth_app
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    restart: on-failure